/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkRecordsRouteImport } from './routes/_authenticated/work-records'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlantingsRouteImport } from './routes/_authenticated/plantings'
import { Route as AuthenticatedMachineryUsageRouteImport } from './routes/_authenticated/machinery-usage'
import { Route as AuthenticatedMachineryRouteImport } from './routes/_authenticated/machinery'
import { Route as AuthenticatedHarvestStockRouteImport } from './routes/_authenticated/harvest-stock'
import { Route as AuthenticatedFieldsRouteImport } from './routes/_authenticated/fields'
import { Route as AuthenticatedFertilizersRouteImport } from './routes/_authenticated/fertilizers'
import { Route as AuthenticatedFertilizerPurchasesRouteImport } from './routes/_authenticated/fertilizer-purchases'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCropsRouteImport } from './routes/_authenticated/crops'
import { Route as AuthenticatedBuyersRouteImport } from './routes/_authenticated/buyers'
import { Route as AuthenticatedAgriculturalWorksRouteImport } from './routes/_authenticated/agricultural-works'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkRecordsRoute =
  AuthenticatedWorkRecordsRouteImport.update({
    id: '/work-records',
    path: '/work-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlantingsRoute = AuthenticatedPlantingsRouteImport.update({
  id: '/plantings',
  path: '/plantings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMachineryUsageRoute =
  AuthenticatedMachineryUsageRouteImport.update({
    id: '/machinery-usage',
    path: '/machinery-usage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMachineryRoute = AuthenticatedMachineryRouteImport.update({
  id: '/machinery',
  path: '/machinery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHarvestStockRoute =
  AuthenticatedHarvestStockRouteImport.update({
    id: '/harvest-stock',
    path: '/harvest-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFieldsRoute = AuthenticatedFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFertilizersRoute =
  AuthenticatedFertilizersRouteImport.update({
    id: '/fertilizers',
    path: '/fertilizers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFertilizerPurchasesRoute =
  AuthenticatedFertilizerPurchasesRouteImport.update({
    id: '/fertilizer-purchases',
    path: '/fertilizer-purchases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCropsRoute = AuthenticatedCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuyersRoute = AuthenticatedBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgriculturalWorksRoute =
  AuthenticatedAgriculturalWorksRouteImport.update({
    id: '/agricultural-works',
    path: '/agricultural-works',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agricultural-works': typeof AuthenticatedAgriculturalWorksRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/crops': typeof AuthenticatedCropsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fertilizer-purchases': typeof AuthenticatedFertilizerPurchasesRoute
  '/fertilizers': typeof AuthenticatedFertilizersRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/harvest-stock': typeof AuthenticatedHarvestStockRoute
  '/machinery': typeof AuthenticatedMachineryRoute
  '/machinery-usage': typeof AuthenticatedMachineryUsageRoute
  '/plantings': typeof AuthenticatedPlantingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/work-records': typeof AuthenticatedWorkRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agricultural-works': typeof AuthenticatedAgriculturalWorksRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/crops': typeof AuthenticatedCropsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fertilizer-purchases': typeof AuthenticatedFertilizerPurchasesRoute
  '/fertilizers': typeof AuthenticatedFertilizersRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/harvest-stock': typeof AuthenticatedHarvestStockRoute
  '/machinery': typeof AuthenticatedMachineryRoute
  '/machinery-usage': typeof AuthenticatedMachineryUsageRoute
  '/plantings': typeof AuthenticatedPlantingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/work-records': typeof AuthenticatedWorkRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agricultural-works': typeof AuthenticatedAgriculturalWorksRoute
  '/_authenticated/buyers': typeof AuthenticatedBuyersRoute
  '/_authenticated/crops': typeof AuthenticatedCropsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fertilizer-purchases': typeof AuthenticatedFertilizerPurchasesRoute
  '/_authenticated/fertilizers': typeof AuthenticatedFertilizersRoute
  '/_authenticated/fields': typeof AuthenticatedFieldsRoute
  '/_authenticated/harvest-stock': typeof AuthenticatedHarvestStockRoute
  '/_authenticated/machinery': typeof AuthenticatedMachineryRoute
  '/_authenticated/machinery-usage': typeof AuthenticatedMachineryUsageRoute
  '/_authenticated/plantings': typeof AuthenticatedPlantingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/work-records': typeof AuthenticatedWorkRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agricultural-works'
    | '/buyers'
    | '/crops'
    | '/dashboard'
    | '/fertilizer-purchases'
    | '/fertilizers'
    | '/fields'
    | '/harvest-stock'
    | '/machinery'
    | '/machinery-usage'
    | '/plantings'
    | '/profile'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/users'
    | '/work-records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agricultural-works'
    | '/buyers'
    | '/crops'
    | '/dashboard'
    | '/fertilizer-purchases'
    | '/fertilizers'
    | '/fields'
    | '/harvest-stock'
    | '/machinery'
    | '/machinery-usage'
    | '/plantings'
    | '/profile'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/users'
    | '/work-records'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agricultural-works'
    | '/_authenticated/buyers'
    | '/_authenticated/crops'
    | '/_authenticated/dashboard'
    | '/_authenticated/fertilizer-purchases'
    | '/_authenticated/fertilizers'
    | '/_authenticated/fields'
    | '/_authenticated/harvest-stock'
    | '/_authenticated/machinery'
    | '/_authenticated/machinery-usage'
    | '/_authenticated/plantings'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/suppliers'
    | '/_authenticated/users'
    | '/_authenticated/work-records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work-records': {
      id: '/_authenticated/work-records'
      path: '/work-records'
      fullPath: '/work-records'
      preLoaderRoute: typeof AuthenticatedWorkRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plantings': {
      id: '/_authenticated/plantings'
      path: '/plantings'
      fullPath: '/plantings'
      preLoaderRoute: typeof AuthenticatedPlantingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/machinery-usage': {
      id: '/_authenticated/machinery-usage'
      path: '/machinery-usage'
      fullPath: '/machinery-usage'
      preLoaderRoute: typeof AuthenticatedMachineryUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/machinery': {
      id: '/_authenticated/machinery'
      path: '/machinery'
      fullPath: '/machinery'
      preLoaderRoute: typeof AuthenticatedMachineryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/harvest-stock': {
      id: '/_authenticated/harvest-stock'
      path: '/harvest-stock'
      fullPath: '/harvest-stock'
      preLoaderRoute: typeof AuthenticatedHarvestStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fields': {
      id: '/_authenticated/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof AuthenticatedFieldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fertilizers': {
      id: '/_authenticated/fertilizers'
      path: '/fertilizers'
      fullPath: '/fertilizers'
      preLoaderRoute: typeof AuthenticatedFertilizersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fertilizer-purchases': {
      id: '/_authenticated/fertilizer-purchases'
      path: '/fertilizer-purchases'
      fullPath: '/fertilizer-purchases'
      preLoaderRoute: typeof AuthenticatedFertilizerPurchasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crops': {
      id: '/_authenticated/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof AuthenticatedCropsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buyers': {
      id: '/_authenticated/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof AuthenticatedBuyersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agricultural-works': {
      id: '/_authenticated/agricultural-works'
      path: '/agricultural-works'
      fullPath: '/agricultural-works'
      preLoaderRoute: typeof AuthenticatedAgriculturalWorksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgriculturalWorksRoute: typeof AuthenticatedAgriculturalWorksRoute
  AuthenticatedBuyersRoute: typeof AuthenticatedBuyersRoute
  AuthenticatedCropsRoute: typeof AuthenticatedCropsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFertilizerPurchasesRoute: typeof AuthenticatedFertilizerPurchasesRoute
  AuthenticatedFertilizersRoute: typeof AuthenticatedFertilizersRoute
  AuthenticatedFieldsRoute: typeof AuthenticatedFieldsRoute
  AuthenticatedHarvestStockRoute: typeof AuthenticatedHarvestStockRoute
  AuthenticatedMachineryRoute: typeof AuthenticatedMachineryRoute
  AuthenticatedMachineryUsageRoute: typeof AuthenticatedMachineryUsageRoute
  AuthenticatedPlantingsRoute: typeof AuthenticatedPlantingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWorkRecordsRoute: typeof AuthenticatedWorkRecordsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgriculturalWorksRoute: AuthenticatedAgriculturalWorksRoute,
  AuthenticatedBuyersRoute: AuthenticatedBuyersRoute,
  AuthenticatedCropsRoute: AuthenticatedCropsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFertilizerPurchasesRoute: AuthenticatedFertilizerPurchasesRoute,
  AuthenticatedFertilizersRoute: AuthenticatedFertilizersRoute,
  AuthenticatedFieldsRoute: AuthenticatedFieldsRoute,
  AuthenticatedHarvestStockRoute: AuthenticatedHarvestStockRoute,
  AuthenticatedMachineryRoute: AuthenticatedMachineryRoute,
  AuthenticatedMachineryUsageRoute: AuthenticatedMachineryUsageRoute,
  AuthenticatedPlantingsRoute: AuthenticatedPlantingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWorkRecordsRoute: AuthenticatedWorkRecordsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
